### ISSUE TITLE
Conditional `NavTab` child

### ISSUE THREAD

**Issue by tombertrand** [chacestew/react-router-tabs#1]
Would it be possible to handle conditional tabs? Currently If I add a condition to display or not a tab it throws an error

![image](https://user-images.githubusercontent.com/19352322/34127466-3d4a8bb4-e40b-11e7-9c32-9a2960364204.png)

```javascript
<RoutedTabs startPathWith={match.url} className="page__tabs">
    <NavTab to={isNew ? '' : '/details'}>Details</NavTab>
    {!isNew && <NavTab to="/merge">Merge</NavTab>}
</RoutedTabs>
```

Here is a potential fix
 
```javascript
const enhancedChildren = React.Children.map(children, tab => {
    if (!tab) return;
...
```

Thanks, great plugin!

**Comment by chacestew** [comment]
Hi there - and sorry for the late reply! This is definitely something that should be supported, so thanks for raising the issue. Feel free to make a pull request with the fix you proposed and I will update the npm version afterwards.

**Comment by tombertrand** [comment]
hi @chacestew I've added the PR 👍

**Comment by chacestew** [comment]
I've merged your addition/fix and published to npm. Happy holidays!
