### ISSUE TITLE
The prop "to" could be an object, instead of a string

### ISSUE THREAD

**Issue by 01abhishekjain** [chacestew/react-router-tabs#12]
https://github.com/chacestew/react-router-tabs/blob/ac816bee7d652f403095dc69249330a1ac3d90bd/src/NavTab.js#L63

The propType validation require **to** to be a string, but it could be an object as well.

For example, I might use NavTab to relay the search part of the URL, like so:

`<NavTab to={{pathname:'some/path', search:this.props.location.search}}>Beam me up!</NavTab>`
instead of 
`<NavTab to={'some/path'}>Beam me up!</NavTab>`

So, I think the validation needs to be updated accordingly. Should I submit a PR for the same?

**Comment by chacestew** [comment]
Hi @01abhishekjain, good spot. Please feel free to submit a PR.

**Comment by 01abhishekjain** [comment]
Submitted a PR:
https://github.com/chacestew/react-router-tabs/pull/13
