### ISSUE TITLE
Be able to reselect a tab

### ISSUE THREAD

**Issue by gabriel-morin-pro** [chacestew/react-router-tabs#14]
Hello

My tabs contains some inner navigation. I need to be able to go back to the default/home tab when I reselect a currently selected tab. Is that already possible?

In short: If I am at `/tab1/subroute` clicking on Tab 1 would send me to `/tab1`

**Comment by chacestew** [comment]
Hi - I must admit I haven't run into a UI case like this yet, so it's a little hard to imagine. I assume you want the same NavTab to point to both `/tab1/subroute` and `/tab1` based on the current location, while keeping the active styling?

**Comment by gabriel-morin-pro** [comment]
This already works, i have sub routes in my tab and it keeps the styling.
What is missing is to be able to re-select an already selected tab to go
back to the root of this tab (clear the sub path in my case)

**Comment by chacestew** [comment]
I see. You can update the `to` prop = root path when that tab is selected, however clicking it won't be possible because NavTabs restrict clicking when they are active.

```js
// NavTab.js - line 40

const onClick = e => {
  if (isActive || disabled) {
    e.preventDefault();
  }
};
```

This was an opinion about normal tab behaviour, but it makes sense to allow an override. Would a prop like `<NavTab allowActiveClick={someBool} />` solve this for you?

**Comment by gabriel-morin-pro** [comment]
It seems like yes. Maybe enableReselect or allowClickOnActiveTab ?

**Comment by chacestew** [comment]
`allowClickOnActive` will work, the more descriptive the better. `disabled` prop should trump this so it would be something like

```js
if (disabled || (isActive && !allowClickOnActive)) e.preventDefault()
```

Feel free to make a PR if you agree, otherwise I will do so later today.

**Comment by chacestew** [comment]
or let me know if you want to supply a PR later and I will wait for it. Have a couple other things needing to be added/changed too :)

**Comment by gabriel-morin-pro** [comment]
Yes it's nice, and no sorry I can't make a PR today.

Thank you and have a great day!
