### ISSUE TITLE
 Initialize example project

### ISSUE THREAD

**Issue by Rudgey84** [chacestew/react-router-tabs#15]
How do I build and run the example project with yarn?

**Comment by Rudgey84** [comment]
Yarn start... had issues with webpack-dev-server. Fix was 'yarn add webpack-cli -D'

**Comment by chacestew** [comment]
I'm not sure why this happened. `webpack-cli` should not be required, as the npm script will target the locally installed webpack-dev-server ([ref](https://github.com/webpack/webpack-dev-server#with-npm-scripts)). The same happens when I test using yarn, so hopefully this was a weird one-off.
