### ISSUE TITLE
Combine NavTab and Route into one element

### ISSUE THREAD

**Issue by all43** [chacestew/react-router-tabs#20]
Not an issue, just suggestion.

It would be nice to have `component` prop for NavTab. It could act like a wrap for `Switch/Route` and will allow to reduce boilerplate.
Example:
 ```
<NavTab to="/admins" component={Admins}>Admins</NavTab>
<NavTab to="/moderators" component={Moderators}>Moderators</NavTab>
<NavTab to="/users" component={Users}>Users</NavTab>
```
would compile to
```
<Switch>
  <Route... />
  <Route... />
  ...
</Switch>
```
block after the last `NavTab` element.

**Comment by chacestew** [comment]
Hi @all43, thanks for taking the time to make a suggestion.

I am not sure how this would be implemented as you suggest, without something like a babel plugin to add code for the `Routes`? Using only React, we would need a new component to hold the Switch+Routes, and use [portals](https://reactjs.org/docs/portals.html) to render each `Route` remotely from each `NavTab`. My idea is already way too mysterious of an abstraction. If you have a different idea of implementing it, please share as this is a very interesting problem in React.

Regardless of implementation, my main concern is this: when creating a wrapper for `Route`, we would also need way to accept all of Route's known props via the `NavTab`. Right now, `NavTab` simply passes all extra props to its final child (usually anchor tag), and any change to that would be breaking.
