### ISSUE TITLE
Close Tab

### ISSUE THREAD

**Issue by cesoftinfo** [chacestew/react-router-tabs#22]
Is there any way to add close icon or some other way to close Tab?

**Comment by chacestew** [comment]
Hi @cesoftinfo - depending on your route setup, this would likely just require a "Close Tab" NavTab with the `to` prop set to the parent route e.g. 3rd item in the example below:

```
/pagewithtabs/tab1 // Tab 1 open
/pagewithtabs/tab2 // Tab 2 open
/pagewithtabs // No tab open
```
