### ISSUE TITLE
How do you use this with Material UI?

### ISSUE THREAD

**Issue by JonathanWilbur** [chacestew/react-router-tabs#24]
Is there anyway I can put a `NavTab` inside of a Material UI `Tab` or vice versa so that it has the visual appearance and effects of a Material UI `Tab` but still the navigation functionality of `NavTab`?

**Comment by chacestew** [comment]
`NavTav` renders whatever children you pass to it, so you should simply be able to nest your Material tab component to achieve this. Note that in this case you shouldn't include the example styles.
