### ISSUE TITLE
Nested Tabs and multiple active classes

### ISSUE THREAD

**Issue by babycourageous** [chacestew/react-router-tabs#3]
Hi - 

Just discovered this component and it works like a charm. I'm hoping that there is a way to accomplish this: 

I have a Parent component with a set of Tabs that each display a Child component that has it's own set of Tabs. When one of the nested Tabs is clicked the parent Tab loses its active state. I would like to still highlight the parent Tab while navigating through the children Tabs. 

Hopefully that makes sense!

Thanks

**Comment by chacestew** [comment]
Hi there - my apologies for not getting back sooner!

Yes, you can accomplish this by setting the prop ```exact={false}``` on the parent NavTabs, this means the active styling will apply for ```/parent``` and ```/parent/child/etc``` paths.

This behaviour is actually meant to be the default (and says so in docs), to keep consistent with how RR4's NavLink behaves, so thanks for bringing that bug to my attention. I will need to consider the breaking cases to decide whether to fix the code or change the docs.

**Comment by chacestew** [comment]
Exact now defaults to false with https://github.com/chacestew/react-router-tabs/commit/5fa305d84ce71df3c02a9daf5dc6fec24a129c6a, so after updating you should be fine.
