### ISSUE TITLE
Using Tabs in a list

### ISSUE THREAD

**Issue by babycourageous** [chacestew/react-router-tabs#4]
I'm curious if there is any way to use the Tabs as part of an unordered list. 
```
<RoutedTabs startPathWith={match.url}>
  <ul>
    {items.map(({ name, slug }) => (
      <li>
        <NavTab
           key={slug}
            to={`/${slug}`}
         >
           {name}
         </NavTab>
       </li>
      ))}
   </ul>
</RoutedTabs>
```
Currently, the `RoutedTabs` component passes all the props to its children so in the case of a list it passes these props to the `li` element instead of the `NavTab` (child of `li`) resulting in its functionality being lost. 

Thanks

**Comment by chacestew** [comment]
In this case, I would recommend not using `RoutedTabs`. It is only helpful when declaring tabs statically to prepend `match.url` to the paths and pass styling props in one place. Here you are already iterating to create the `NavTabs`, so you can prepend/style it yourself:

```js
<ul>
    {items.map(({ name, slug }) => (
      <li>
        <NavTab
            key={slug}
            to={`${match.url}/${slug}`}
            className="nav-tab"
            activeClassName="active"
         >
           {name}
         </NavTab>
       </li>
      ))}
   </ul>
```

Let me know if this suit your needs. The next minor patch will give `NavTab` the default class and active class without needing to wrap it in `RoutedTabs`, as I see these components should be decoupled further.

**Comment by chacestew** [comment]
I forgot to mention that if you don't use `RoutedTabs` and you are using the provided stylesheet, ~you will need to add the class `"react-router-tabs"`~ in some containing element for the tab styles to work. I will reference back to this issue when that is changed. 

Edit: no longer necessary! If you are using the default stylesheet or similar nesting, just update to get the amended stylesheet.

**Comment by chacestew** [comment]
Further update - you can simplify your code to just

```js
...
<NavTab
   key={slug}
   to={`${match.url}/${slug}`}
>
...
```
as the classes will be provided by default (https://github.com/chacestew/react-router-tabs/commit/5fa305d84ce71df3c02a9daf5dc6fec24a129c6a) without needing `RoutedTabs`.

Thanks for trying out the library and raising these issues.

**Comment by babycourageous** [comment]
Thanks @chacestew !
(sorry I haven't gotten to say thanks sooner, been outta town and just catching up to a bunch)
